### ISSUE TITLE
ck install package:imagenet-2012-val   fails

### ISSUE THREAD

**Issue by maxwillzq** [ctuning/ck-env#101]
The error message:
```
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   CK detected a PROBLEM in the third-party CK package:

   CK package:           imagenet-2012-val
   CK repo:              ck-env
   CK repo URL:          https://github.com/ctuning/ck-env
   CK package URL:       https://github.com/ctuning/ck-env/tree/master/package/imagenet-2012-val
   Issues URL:           https://github.com/ctuning/ck-env/issues
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Please, submit the log to the authors of this external CK package at "https://github.com/ctuning/ck-env/issues" to collaboratively fix this problem!

CK error: [package] package installation failed!
```

**Comment by psyhtest** [comment]
Hi @maxwillzq, Can you please share more of the log? Do you have `wget` installed?

**Comment by psyhtest** [comment]
@maxwillzq Thanks for your interest in CK!

I was very surprised to see this last night as many of the [MLPerf Inference v0.5 submitters](https://mlperf.org/inference-results/) used this package without any problems including [Alibaba](https://github.com/mlperf/inference_results_v0.5/tree/master/closed/Alibaba/measurements/alibaba_HanGuang/resnet/Server#download-the-imagenet-dataset), [Google](https://github.com/mlperf/inference_results_v0.5/tree/master/closed/Google/measurements/tpu-v3.8x1/resnet/server#publictionattribution), [Intel](https://github.com/mlperf/inference_results_v0.5/tree/master/closed/Intel/code/resnet/onnx#datasets) and [Qualcomm](https://source.codeaurora.org/quic/mlperfqc/snpe-mlperf-net-run/tree/README.md).

But it seems that the URL is no longer valid:
```
$ ck install package:imagenet-2012-val

Searching if CK environment for this package already exists using:
  * Tags: image-classification,dataset,imagenet,2012,val,full,raw,original,jpg,caffe,ilsvrc2012,channel-stable,host-os-linux-64,target-os-linux-64,64bits

CK environment not found for this package ...

*** Installation path used: /home/anton/CK_TOOLS/dataset-imagenet-ilsvrc2012-val

Installing to /home/anton/CK_TOOLS/dataset-imagenet-ilsvrc2012-val

Checking whether '/home/anton/CK_TOOLS/dataset-imagenet-ilsvrc2012-val/ILSVRC2012_img_val.tar' already exists ...

Downloading ILSVRC'12 validation dataset from 'http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_img_val.tar' ...
--2019-11-07 09:29:31--  http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_img_val.tar
Resolving www.image-net.org (www.image-net.org)... 171.64.68.16
Connecting to www.image-net.org (www.image-net.org)|171.64.68.16|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-11-07 09:29:31 ERROR 404: Not Found.

Error: Downloading ILSVRC'12 validation set from 'http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_img_val.tar' failed!
```
It fails without CK too:
```
$ wget http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_img_val.tar
--2019-11-07 10:09:28--  http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_img_val.tar
Resolving www.image-net.org (www.image-net.org)... 171.64.68.16
Connecting to www.image-net.org (www.image-net.org)|171.64.68.16|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-11-07 10:09:29 ERROR 404: Not Found.
```
Perhaps the link is temporarily unavailable. Or perhaps it's been permanently removed. Hmm.

We know that ImageNet is available for download via torrents. We will see if we can make an alternative CK package.

**Comment by psyhtest** [comment]
FYI: We have [started](https://groups.google.com/forum/m/#!topic/mlperf/3I0bh20uCNA) to discuss the ImageNet (un)availability in the MLPerf working group.

**Comment by gfursin** [comment]
Extra ideas here: https://dev.codereef.ai/portal/c/package/imagenet-2012-aux

**Comment by Arthur1975** [comment]
is the issue fixed?  Could you advise how?  I also encountered the error message while running ck install package:imagenet-2012-aux

   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   CK detected a PROBLEM in the third-party CK package:

   CK package:           imagenet-2012-aux
   CK repo:              ck-env
   CK repo URL:          https://github.com/ctuning/ck-env
   CK package URL:       https://github.com/ctuning/ck-env/tree/master/package/imagenet-2012-aux
![IMG_4457](https://user-images.githubusercontent.com/60458319/73424274-4d8dff00-4369-11ea-9dbd-fce3dfe69f64.jpg)
   Issues URL:           https://github.com/ctuning/ck-env/issues
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Please, submit the log to the authors of this external CK package at "https://github.com/ctuning/ck-env/issues" to collaboratively fix this problem!

CK error: [package] package installation failed!

**Comment by gfursin** [comment]
As suggested by @martinlightmatter, I updated those 2 CK packages (imagenet-2012-val and imagenet-2012-train) with the following error message:

```
D:\>ck install package:imagenet-2012-val

=============================================================================================
Unfortunately, ImageNet 2012 validation set is no longer publicly available
and this CK meta-package can not automatically download it!

See the related discussions:
* https://CodeReef.ai/portal/c/package/imagenet-2012-val
* https://github.com/pytorch/vision/issues/1453
* https://github.com/ctuning/ck-env/issues/101

However, if you already have it installed on your machine, you can detect
and register it to work with CK workflows using this command:

$ ck detect soft:dataset.imagenet.val --search_dir={directory where the dataset is installed}
=============================================================================================

CK error: [package] this package has a known problem - see the message above!
```

I uploaded the latest versions of those packages to the CodeReef platform:

* https://codereef.ai/portal/c/package/imagenet-2012-val/
* https://codereef.ai/portal/c/package/imagenet-2012-train/

One needs to update the ck-env repo to see this message:
```
$ ck pull repo:ck-env
```

**Comment by gfursin** [comment]
Somehow module:package stopped processing packages with "problem":"yes" meta. I fixed that problem. I also added a note about how to download ImageNet via Academic Torrents. I close this ticket ...
