### ISSUE TITLE
Create soft:compiler.gfortran 

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-env#11]
This blocks [issue #2](https://github.com/ctuning/ck-math/issues/2) in the [ck-math](https://github.com/ctuning/ck-math) repository.

**Comment by gfursin** [comment]
Done: you can check if via:
$ ck detect soft:compiler.gfortran

**Comment by psyhtest** [comment]
It works, thanks! Any particular reason the tags do not include "fortran":
```
  "tags": [
    "compiler",
    "gfortran",
    "lang-f77",
    "lang-f90",
    "lang-f95"
  ]
```

**Comment by gfursin** [comment]
Hmm, that's right actually - genius ;) ! Added! Thanks!

**Comment by psyhtest** [comment]
Another related thing is that GCC (GNU C compiler) also has tags: `lang-f77,lang-f90,lang-f95`. Should they be removed?

By the way, to avoid confusion I would recommend to update the compiler names:
- GNU C compiler
- GNU Fortran compiler

**Comment by gfursin** [comment]
I have removed above tags (you will still see them on the previously registered GCC, but it should dissapear on clean setups or if you reregister env, or try experimental "ck refresh env"). I also changed the names as you suggested!
