### ISSUE TITLE
Cleanup src package dir even if set "PACKAGE_SKIP_CLEAN_SRC_DIR": "YES"

### ISSUE THREAD

**Issue by DVEfremov** [ctuning/ck-env#19]
**step to reproduce** 

* Set meta to skip cleanup and clone src for example at 
~/CK/ck-caffe/package/lib-caffe-bvlc-opencl-libdnn-clblast-universal/.cm/meta.json
``` "PACKAGE_SKIP_CLEAN_SRC_DIR": "YES",
```

* compile some program with dependent packages for example 
```$ck compile program:caffe-time-opencl ```

* from log you cans see src removed and git clone process applied

**Comment by gfursin** [comment]
This is not a bug - this is a feature ;) . In fact, this is an unfortunately ambigious key which says whether to keep src dir or not AFTER package is built ... If you want to skip removal of src and git clone, you need to change the key "PACKAGE_GIT": "YES" to "NO" - then src will not be deleted and cloning will not happen. This is useful when trying to rebuild large packages without downloading them ...
