### ISSUE TITLE
There is no SLEEP command on Windows

### ISSUE THREAD

**Issue by Chunosov** [ctuning/ck-env#20]
Windows script _download-and-install-package/install.bat_ contains calls like _sleep 2_, but Windows tells
```
'sleep' is not recognized as an internal or external command,
operable program or batch file.
```
sleep command is found in _c:\MinGW\msys\1.0\bin\_ directory.
Is should be mentioned about that we have to add this dir to PATH variable or use msys console.

**Comment by gfursin** [comment]
Thanks! You are right - I thought it was internal Windows command, but it's not - I substituted it with "timeout /t 2 /nobreak" and committed. In such scripts I want to use only native Windows commands without extra deps to be portable and small...
