### ISSUE TITLE
Windows: should search GCC in c:\MinGW

### ISSUE THREAD

**Issue by Chunosov** [ctuning/ck-env#21]
Currently CK can't find installed gcc compiler in dir C:\MinGW but it is default installation path for MinGW. At least for online installer:
![image](https://cloud.githubusercontent.com/assets/22535028/22812340/bac8c900-ef76-11e6-9604-b4af0f808739.png)

**Comment by dsavenko** [comment]
Clarification: `ck detect soft:compiler.gcc` must be able to find gcc inside of C:\MinGW

**Comment by Rhymmor** [comment]
Done. See PR #23

**Comment by gfursin** [comment]
Thanks a lot! I close this ticket!
