### ISSUE TITLE
Recognise symlinks when detecting software installations

### ISSUE THREAD

**Issue by dsavenko** [ctuning/ck-env#22]
For now, CK doesn't recognise symlinks. So, when detecting installation of some library (e.g. `libhdf5.so` for ck-caffe), it asks to choose from 3 variants, two of them being symlinks to the other one. It would be better if CK understands they're symlinks and doesn't show them as separate installations.

**Comment by gfursin** [comment]
I believe I fixed that - do you mind to check it with HDF5 for example, please? Thanks!

**Comment by dsavenko** [comment]
Checked on my machine with HDF5, looks like it's indeed fixed. Closing.
