### ISSUE TITLE
ar and ranlib problems with Caffe installation

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-env#34]
I hit a couple of snags when installing Caffe (`package:lib-caffe-bvlc-master-cpu-universal`) on a CentOS 7 development board. 

The original compiler (`gcc-4.8.5`) was quite old which is possibly why I was having segfaults when running `program:caffe-classification`. I upgraded to `gcc-5.3.1` [as follows](http://stackoverflow.com/questions/36327805/how-to-install-gcc-5-3-with-yum-on-centos-7-2):
```
sudo yum install centos-release-scl
sudo yum install devtoolset-4-gcc*
scl enable devtoolset-4 bash
```
The new compiler was placed into `/opt/rh/devtoolset-4/root/usr/bin/`. Initially, CK wouldn't pick it up, but I linked this directory from `$CK_TOOLS`. So far, so good:
```
$ ck show env --tags=gcc                                                                                                                                        
Env UID:         Target OS: Bits: Name:          Version: Tags:

f2e1b60b46c044ad   linux-64    64 GNU C compiler 5.3.1    64bits,compiler,gcc,host-os-linux-64,lang-c,lang-cpp,target-os-linux-64,v5,v5.3,v5.3.1
b1aaa7b21081bcea   linux-64    64 GNU C compiler 4.8.5    64bits,compiler,gcc,host-os-linux-64,lang-c,lang-cpp,target-os-linux-64,v4,v4.8,v4.8.5
```

When installing `ck-caffe:package:lib-caffe-bvlc-master-universal-cpu`, however, the build failed due to a linking problem. I inspected the contents of `CMakeFiles/proto.dir/link.txt` both in the successful installation (with `gcc-4.8.5`):
```
# $CK_TOOLS/lib-caffe-bvlc-master-cpu-trunk-gcc-4.8.5-linux-64/obj/src/caffe/CMakeFiles/proto.dir/link.txt
/usr/bin/ar qc ../../lib/libproto.a  CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
/usr/bin/ranlib ../../lib/libproto.a
```
and in the failed installation:
```
# $CK_TOOLS/lib-caffe-bvlc-master-cpu-trunk-gcc-5.3.1-linux-64/obj/src/caffe/CMakeFiles/proto.dir/link.txt
"" qc ../../lib/libproto.a  CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
/usr/bin/ranlib ../../lib/libproto.a
```
As can be seen, CK didn't provide anything for `ar` and used the default path to `ranlib`. Once I manually changed `$CK_TOOLS/lib-caffe-bvlc-master-cpu-trunk-gcc-5.3.1-linux-64/obj/src/caffe/CMakeFiles/proto.dir/link.txt` as follows:
```
"$CK_TOOLS/opt-rh-devtoolset-4-root-usr-bin/gcc-ar" qc ../../lib/libproto.a  CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
"$CK_TOOLS/opt-rh-devtoolset-4-root-usr-bin/gcc-ranlib" ../../lib/libproto.a
```
I was able to rerun `make install` manually.

One additional snag was that CK wouldn't register Caffe because the installation dir looked as follows:
```
drwxrwxr-x. 3 4096 May 14 01:49 include
drwxrwxr-x. 2 4096 May 14 01:49 lib64
drwxrwxr-x. 3 4096 May 14 01:49 python
```
while CK was expecting to find `libcaffe.so` under `lib`. I temporarily resolved this by making a symbolic link from `install/lib64` to `install/lib` and rerunning `ck detect soft:lib.caffe` manually.

**Comment by gfursin** [comment]
I believe I fixed all above issues (improved soft:compiler.gcc and package:*caffe*) ... I close this ticket. If you find somethings else, just open another ticket...
