### ISSUE TITLE
MacOS dynamic library issues

### ISSUE THREAD

**Issue by mminutoli** [ctuning/ck-env#49]
https://github.com/ctuning/ck-env/blob/a5f49fa14243e69a7983655138f4ec2f272d584d/os/macos-64/.cm/meta.json#L41

This is the line that was causing issue with boost on my system.

".so" should be ".dylib"

**Comment by gfursin** [comment]
Oh, embarrasing - thanks for spotting it! Just fixed that! Hope it will work now!
https://github.com/ctuning/ck-env/commit/bdd4045dbe7ce3e051e1c3fe00b0bfd53bef560d

**Comment by gfursin** [comment]
I guess it's fixed now. Thanks!
