### ISSUE TITLE
Target_device_id arg check fails when there's multiple devices connected to host machine

### ISSUE THREAD

**Issue by TelmoARM** [ctuning/ck-env#64]
Hi there, 

We found a bug with the setup function in ck-env/module/soft/module.py line 351. 

If you have multiple devices connected to a host machine and run the following command line:
$ ck install package:xxxxxxxxxxxxxxxxxxxxxxx --target_os=android24-arm64 --target_device_id=XXXXXXXXX

the device_target_id argument isn't recognised and the following error pops-up:
CK error: [package] more than one remote device - specify via --device_id!

Asking us to set the device_id.

We changed line 351 from --target_device_id to device_id and rerun the first command it runs successfully

**Comment by gfursin** [comment]
Hi! I did a slightly different change to keep backwards compatibility (there was indeed a mix up between "target_device_id" and "device_id" at some point :( ):
```
    tdid=i.get('target_device_id','')
    if tdid=='': tdid=i.get('device_id','')
```
I just committed this change - may I ask you to check it if it will work for you!

**Comment by TelmoARM** [comment]
Hi, 

Thanks for the quick reply. We have integrated the fix and we can confirm it fixed.

Telmo

**Comment by psyhtest** [comment]
Closing as resolved.
