### ISSUE TITLE
Accidental vars redefenition when installind deps for a package

### ISSUE THREAD

**Issue by Chunosov** [ctuning/ck-env#65]
Investigating the reasons of issue https://github.com/ctuning/ck-request-asplos18-caffe-intel/issues/14 I've found that caffe packages has similar var in its meta:
```
      "PACKAGE_URL_ANDROID": "https://github.com/BVLC/caffe",
      "PACKAGE_URL_LINUX": "https://github.com/BVLC/caffe",
      "PACKAGE_URL_WINDOWS": "https://github.com/BVLC/caffe", 
```
But if there is some dep need to be installed during caffe installation, these vars can override `PACKAGE_URL` var from dep's meta. It is because of `download-and-install-package` script contains such a code
```
if [ "$PACKAGE_URL_LINUX" != "" ] ; then
           PACKAGE_URL=$PACKAGE_URL_LINUX
fi
```
Not sure how not fix it properly.
I'd suggest to modify mentioned code as 
```
if [ "$PACKAGE_URL_LINUX" != "" ] ; then
    if [ "$PACKAGE_URL" == "" ] ; then
           PACKAGE_URL=$PACKAGE_URL_LINUX
    fi
fi
```
i.e. we only redefine the var if it is not set yet. But I'm not sure which side effects it can involve. Also there are lot of another similar code pieces in that script but with different vars.
@gfursin what do you think?

**Comment by gfursin** [comment]
No, this is just a bug in my last commit - sorry about that. I believe I fixed that now...
