### ISSUE TITLE
Caffe installation offers two choices for HDF5

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-env#68]
It's not an error but could be quite annoying (especially if you don't know which one you need).
```
*** Dependency 7 = lib-hdf5 (HDF5 library):

More than one environment found for "HDF5 library" with tags="lib,hdf5" and setup={"target_os_bits": "64", "host_os_uoa": "linux-64", "target_os_uoa": "linux-64"}:

0) HDF5 library (static) - v1.8.16 (64bits,hdf5,host-os-linux-64,lib,target-os-linux-64,v1,v1.8,v1.8.16,vstatic (263445893b9b9656))
1) HDF5 library - v1.8.16 (64bits,hdf5,host-os-linux-64,lib,target-os-linux-64,v1,v1.8,v1.8.16 (818659942168fb91))
```

I believe the static version was added to support [CK-Cluster](https://github.com/ctuning/ck-cluster18).

**Comment by gfursin** [comment]
I believe I fixed it by changing tags hdf5 to hdf5-static in related soft/package to avoid mixing them up ... Seems to be working fine now ... I close this ticket.
