### ISSUE TITLE
Can't make Bazel 17.2 package on aarch64 platform

### ISSUE THREAD

**Issue by bellycat77** [ctuning/ck-env#80]
Building process fail down - error arises

**Comment by psyhtest** [comment]
Which error exactly? How about Bazel [0.18.x](https://github.com/bazelbuild/bazel/releases/tag/0.18.0) and [0.19.x](https://github.com/bazelbuild/bazel/releases/tag/0.19.0)?

**Comment by bellycat77** [comment]
The reason was in "native" support aarch64-platform in 17th version. That support conflicts with patches which was applied for older versions. **Fixed**
